version: 2

sources:
  - name: majmoud
    description: 'Utilisation de la base de données majmoud dans postgres'
    database: majmoud
    schema: public

    tables:
      - name: tracks
        description: 'Definition du schema de la table tracks'
        columns: 
          - name: '"TrackId"'
            tests:
              - unique
              - not_null

          - name: '"Name"'

          - name: '"AlbumId"'
            tests:
              - not_null

          - name: '"MediaTypeId"'
            tests:
              - not_null

          - name: '"GenreId"'
            tests:
              - not_null

          - name: '"Composer"'

          - name: '"Milliseconds"'

          - name: '"Bytes"'

          - name: '"UnitPrice"'

      - name: albums
        description: 'Definition du schema de la table albums'
        columns: 
          - name: '"AlbumId"'
            tests:
              - unique
              - not_null

          - name: '"Title"'

          - name: '"ArtistId"'
            tests:
              - not_null


      - name: artists
        description: 'Definition du schema de la table artists'
        columns: 
          - name: '"ArtistId"'
            tests:
              - unique
              - not_null

          - name: '"Name"'


      - name: invoices
        description: 'Definition du schema de la table invoices'
        columns: 
          - name: '"InvoiceId"'
            tests:
              - unique
              - not_null

          - name: '"CustomerId"'
            tests:
              - not_null

          - name: '"InvoiceDate"'

          - name: '"BillingAddress"'
          - name: '"BillingCity"'
          - name: '"BillingState"'
          - name: '"BillingCountry"'
          - name: '"BillingPostalCode"'
          - name: '"Total"'

      
      - name: invoice_items
        description: 'Definition du schema de la table invoice_items'
        columns: 
          - name: '"InvoiceLineId"'
            tests:
              - unique
              - not_null

          - name: '"InvoiceId"'
            tests:
              - not_null

          - name: '"TrackId"'
            tests:
              - not_null

          - name: '"UnitPrice"'
          - name: '"Quantity"'

      
      

